/* Generated by Yosys 0.17 (git sha1 6f9602b4c, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "counter.v:1.1-21.10" *)
module counter(out, clk, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "counter.v:9.41-9.46" *)
  wire _08_;
  (* src = "counter.v:9.41-9.46" *)
  wire _09_;
  (* src = "counter.v:9.41-9.46" *)
  wire _10_;
  (* src = "counter.v:9.41-9.46" *)
  wire _11_;
  (* src = "counter.v:9.41-9.46" *)
  wire _12_;
  (* src = "counter.v:9.41-9.46" *)
  wire _13_;
  (* src = "counter.v:9.41-9.46" *)
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "counter.v:2.41-2.44" *)
  wire _21_;
  (* src = "counter.v:2.41-2.44" *)
  wire _22_;
  (* src = "counter.v:2.41-2.44" *)
  wire _23_;
  (* src = "counter.v:2.41-2.44" *)
  wire _24_;
  (* src = "counter.v:2.41-2.44" *)
  wire _25_;
  (* src = "counter.v:2.41-2.44" *)
  wire _26_;
  (* src = "counter.v:2.41-2.44" *)
  wire _27_;
  (* src = "counter.v:2.41-2.44" *)
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "counter.v:3.41-3.44" *)
  input clk;
  wire clk;
  (* src = "counter.v:9.41-9.46" *)
  wire [7:0] count;
  (* src = "counter.v:2.41-2.44" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "counter.v:4.41-4.46" *)
  input reset;
  wire reset;
  ANX1_CV _38_ (
    .A(_22_),
    .B(_21_),
    .Y(_15_)
  );
  ANX1_CV _39_ (
    .A(_23_),
    .B(_15_),
    .Y(_16_)
  );
  EOX1_CV _40_ (
    .A(_23_),
    .B(_15_),
    .Y(_09_)
  );
  ANX1_CV _41_ (
    .A(_24_),
    .B(_16_),
    .Y(_17_)
  );
  EOX1_CV _42_ (
    .A(_24_),
    .B(_16_),
    .Y(_10_)
  );
  ANX1_CV _43_ (
    .A(_25_),
    .B(_17_),
    .Y(_18_)
  );
  EOX1_CV _44_ (
    .A(_25_),
    .B(_17_),
    .Y(_11_)
  );
  ANX1_CV _45_ (
    .A(_26_),
    .B(_18_),
    .Y(_19_)
  );
  EOX1_CV _46_ (
    .A(_26_),
    .B(_18_),
    .Y(_12_)
  );
  NDX1_CV _47_ (
    .A(_27_),
    .B(_19_),
    .Y(_20_)
  );
  EOX1_CV _48_ (
    .A(_27_),
    .B(_19_),
    .Y(_13_)
  );
  ENX1_CV _49_ (
    .A(_28_),
    .B(_20_),
    .Y(_14_)
  );
  EOX1_CV _50_ (
    .A(_22_),
    .B(_21_),
    .Y(_08_)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _51_ (
    .CK(clk),
    .D(count[0]),
    .Q(out[0]),
    .QN(_30_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _52_ (
    .CK(clk),
    .D(count[1]),
    .Q(out[1]),
    .QN(_31_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _53_ (
    .CK(clk),
    .D(count[2]),
    .Q(out[2]),
    .QN(_32_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _54_ (
    .CK(clk),
    .D(count[3]),
    .Q(out[3]),
    .QN(_33_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _55_ (
    .CK(clk),
    .D(count[4]),
    .Q(out[4]),
    .QN(_34_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _56_ (
    .CK(clk),
    .D(count[5]),
    .Q(out[5]),
    .QN(_35_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _57_ (
    .CK(clk),
    .D(count[6]),
    .Q(out[6]),
    .QN(_36_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "counter.v:14.4-19.7" *)
  DFSRQNX1_CV _58_ (
    .CK(clk),
    .D(count[7]),
    .Q(out[7]),
    .QN(_29_),
    .R(reset),
    .S(1'h0)
  );
  assign count[0] = _30_;
  assign _22_ = out[1];
  assign _21_ = out[0];
  assign _23_ = out[2];
  assign count[2] = _09_;
  assign _24_ = out[3];
  assign count[3] = _10_;
  assign _25_ = out[4];
  assign count[4] = _11_;
  assign _26_ = out[5];
  assign count[5] = _12_;
  assign _27_ = out[6];
  assign count[6] = _13_;
  assign _28_ = out[7];
  assign count[7] = _14_;
  assign count[1] = _08_;
endmodule
